### ISSUE TITLE
Setup base boilerplate with Express, Passport, EJS & MongoDB.

### ISSUE THREAD

**Issue by stmoerman** [Scopeweb/agency-manager#2]
Try and create a reusable boilerplate which consists of Express, Passport, EJS, and MongoDB.

Commit this to another repository and call it mongo-boilerplate so we have a reusable boilerplate for future projects.

**Comment by MrDemonWolf** [comment]
Added [repo](https://github.com/Scopeweb/mongo-boilerplate)
