### ISSUE TITLE
Create dashboard page and route

### ISSUE THREAD

**Issue by stmoerman** [Scopeweb/agency-manager#3]
Within the application add the following route. Keep in mind that users need to be authenticated before they can view the dashboard.

+ **Route name**: Show
+ **Path**: /dashboard
+ **HTTP Verb**: GET
+ **Purpose**: Show and retrieve all information belonging to either an Admin user or Client user.

**Comment by MrDemonWolf** [comment]
Dashboard user must be  authenticated and it checks the role in the database to show content depending on use,.
