### ISSUE TITLE
Setup signup page and route

### ISSUE THREAD

**Issue by stmoerman** [Scopeweb/agency-manager#5]
Within the application add the following route. Keep in mind that users need to be authenticated before they can view the dashboard. Make sure in the navbar the username is displayed.

+ **Route name**: Register
+ **Path**: /register
+ **HTTP Verb**: POST
+ **Purpose**: Creates a new user, then redirects to the dashboard.

**Comment by MrDemonWolf** [comment]
Users can signup with username + email +password.  There username is in a UL inside a LI.  And dashboard is locked down with middleware to check if `req.user` is in the request.
