### ISSUE TITLE
Setup forgot password page and route

### ISSUE THREAD

**Issue by stmoerman** [Scopeweb/agency-manager#8]
Within the application add the following route. Keep in mind that users need to be authenticated before they can view the dashboard.

+ **Route name**: Reset password
+ **Path**: /forgot
+ **HTTP Verb**: PUT
+ **Purpose**: Sends a user the password reset email (uniquely generated) allowing them to reset their password with a double confirmation field.

**Comment by MrDemonWolf** [comment]
Works now.
